- README.md
- docs/BUILD.bazel
- docs/pmd.md
- example/.aspect/cli/config.yaml
- example/BUILD.bazel
- example/MODULE.bazel
- example/WORKSPACE.bazel
- example/lint.bzl
- example/lint.sh
- example/pmd.xml
- example/src/BUILD.bazel
- example/src/Foo.java
- lint/BUILD.bazel
- lint/pmd.bzl
Possibly an alternative to https://github.com/buildfoundation/bazel_rules_pmd/
> feat: add PMD for Java

- BUILD.bazel
- MODULE.bazel
- README.md
- go.mod
- plugin.go
Demo: [![asciicast](https://asciinema.org/a/xQWU1Wc1JINOubeguDDQbBqcq.svg)](https://asciinema.org/a/xQWU1Wc1JINOubeguDDQbBqcq)
> feat: print nicer output from plugin

- LICENSE
The good parts will be in aspect-cli and Workflows to present the lint results.
> re-license as Apache 2

- README.md
- docs/formatting.md
- example/BUILD.bazel
- example/tools/BUILD
- example/tools/lint.bzl
- Style (white-space, formatting, etc...)
Ran `bazel build :format`
> style: recommend format as an alias in root BUILD

- .github/workflows/ci.yaml
- example/.bazelrc
- example/lint.sh
- example/test/lint_test.bats
---
- Chore (any other change that doesn't affect source or test files, such as configuration)
> ci: add integration testing

- docs/format.md
- docs/ruff.md
- lint/ruff.bzl
Fixes #42
---
`bazel run tools:ruff` on my M1 Mac
> fix: workaround Bazel extract bug

- docs/format.md
- format/private/formatter_binary.bzl
---
- Style (white-space, formatting, etc...)
- Manual : ran the formatter. Will add some bats tests for this next.
> refactor: reduce duplication in formatter lang:tool mapping

- docs/eslint.md
- example/MODULE.bazel.lock
- example/src/subdir/.eslintrc.cjs
- example/src/subdir/BUILD.bazel
- example/src/subdir/index.js
- example/test/lint_test.bats
- example/tools/lint.bzl
- lint/eslint.bzl
Equivalent of #60 which did this for ruff
> feat: allow multiple eslint configs in one aspect definition

- MODULE.bazel
- example/MODULE.bazel
- example/WORKSPACE.bazel
- lint/eslint.bzl
ran `bazel lint` in aspect's silo repo
> fix(eslint): declare copy_to_bin toolchains for bazel-lib 2.0 compat

- docs/eslint.md
- lint/eslint.bzl
> docs: explain which production of ts_project to lint

- README.md
> chore: explain why we don't add mypy here

- lint/ruff.bzl
- Suggested release notes are provided below: Python test files are now linted when using ruff_aspect.
> Add ruff aspect to py_test

- example/test/BUILD.bazel
- example/tools/lint.bzl
- lint/eslint.bzl
- lint/flake8.bzl
- lint/pmd.bzl
- lint/ruff.bzl
- lint/shellcheck.bzl
> fix: filter out generated files from linting

- MODULE.bazel
- example/.aspect/cli/config.yaml
- example/.clang-format
- example/.golangci.yaml
- Chore (any other change that doesn't affect source or test files, such as configuration)
> chore: pre-commit run --all-files

- docs/linting.md
- example/test/BUILD.bazel
- lint/eslint.bzl
- lint/flake8.bzl
- lint/golangci-lint.bzl
- lint/pmd.bzl
- lint/private/lint_aspect.bzl
- lint/ruff.bzl
- lint/shellcheck.bzl
---
well, it's a tags=manual test. I should make lint_test have an expected_exit_code.
> feat: escape hatch from is_source filtering

- format/private/format.sh
- format/repositories.bzl
- format/test/format_test.bats
> fix: pass flag to shfmt to ignore passed files

- README.md
- docs/format.md
- example/.clang-format
- example/.golangci.yaml
- example/WORKSPACE.bazel
- example/WORKSPACE.bzlmod
- example/pnpm-lock.yaml
- example/src/config.yaml
- example/tools/BUILD
- format/private/format.sh
- format/private/formatter_binary.bzl
- format/repositories.bzl
- format/test/BUILD.bazel
- format/test/format_test.bats
> feat: add yamlfmt for YAML

- format/private/format.sh
> ruff: force exclude honoring in check mode too

- docs/formatting.md
> docs: indicate how to configure formatters

- example/tools/format/BUILD.bazel
- format/repositories.bzl
---
- Chore (any other change that doesn't affect source or test files, such as configuration)
> chore: add terraform_linux_aarch64

- docs/format.md
- example/WORKSPACE.bazel
- example/WORKSPACE.bzlmod
- example/tools/format/BUILD.bazel
- format/defs.bzl
- format/multitool.lock.json
- format/private/formatter_binary.bzl
- format/repositories.bzl
Also give users control of the 'jobs' parameter
---
BREAKING CHANGES:
- fetch_terraform() has been removed, get it from @multitool instead
> feat: provide a default for Terraform formatter

- README.md
- docs/formatting.md
- docs/linting.md
- example/tools/format/BUILD.bazel
Noticed in 1.0 API review that we should promote Workflows, that's how we monetize my work in this repo.
None
> chore: update docs for 1.0

- README.md
- docs/formatting.md
- format/README.md
- lint/README.md
Want to take a first PR review? :)
---
None
> docs: add 'how to add formatter'

- example/tools/format/BUILD.bazel
- format/BUILD.bazel
- format/defs.bzl
> fix: format[_test] macros handle common attrs

- docs/eslint.md
- docs/flake8.md
- docs/pmd.md
- example/WORKSPACE.bazel
- example/WORKSPACE.bzlmod
- format/repositories.bzl
- lint/BUILD.bazel
- lint/eslint.bzl
- lint/flake8.bzl
- lint/pmd.bzl
Also move fetch_pmd into pmd.bzl like ruff and vale.
None
> docs: update install docs for non-multitool linters

- docs/flake8.md
- lint/flake8.bzl
- Update the flake8 documentation example to reflect the v0.18.0 changes
> Update flake8 docs

- README.md
- example/MODULE.bazel
- example/WORKSPACE.bazel
- example/src/hello.rs
- example/tools/format/BUILD.bazel
- format/private/format.sh
- format/private/formatter_binary.bzl
- format/test/BUILD.bazel
- format/test/format_test.bats
Picking up #132 again
---
Rust code may now be formatted by rustfmt
> feat: add rustfmt

- README.md
- docs/linting.md
> docs: clarify warning vs error

- format/private/format.sh
It seems to be more useful to display real time than user time for formatting and format checking.
---
- Searched for relevant documentation and updated as needed: yes (the video/gif? is largely outdated, but I'm not sure how to update)
- Breaking change (forces users to change their own code or config): yes (if user parses the bazel output to collect statistics)
Formatting and format checking now display a different message.
For example, instead of `Formatted Python in 0m0.004s` where time is `user time`, it is now `Formatted Python in 0m0.024s seconds` where time is `real time/wall-clock`.
`bazel //tools:format` or `bazel //tools:format.check`
> chore: Real time instead of user time when formatting

- MODULE.bazel
- example/MODULE.bazel
- example/WORKSPACE.bazel
> chore(deps): example update to rules_js2 RC

- example/tools/format/BUILD.bazel
> chore: show less noisy prettier in example

- example/tools/format/BUILD.bazel
see #256
fyi @psalaberria002 
---
None
> prettier log level followup

- .github/workflows/mirror.yml
> feat: auto-update multitool versions

- format/private/format.sh
fix https://github.com/aspect-build/rules_lint/issues/255
> fix(format): print FIX_CMD only when check

- .github/workflows/mirror.yml
Hopefully fixes https://github.com/aspect-build/rules_lint/pull/288 where it created two different commits; the second one reverted the first
> refactor: combine mirroring into one step

- example/tools/lint/BUILD.bazel
> Fix ironic typo

- README.md
- example/.clang-tidy
- example/lint.sh
- example/src/cpp/lib/get/.clang-tidy
- example/src/cpp/lib/get/get-time.cc
- example/src/cpp/lib/get/get-time.h
- example/src/cpp/lib/hello-time.cc
- example/src/cpp/lib/hello-time.h
- example/src/cpp/lib/xhello-time.h
- example/src/cpp/main/hello-greet-with-error.cc
- example/src/cpp/main/hello-greet.cc
- example/src/cpp/main/hello-world.cc
- example/src/hello.cpp
- example/src/hello.graphql
- example/tools/format/BUILD.bazel
Also
- update README with newer asciinema
- mention clang-format landed in README
---
> chore: run formatter

- example/MODULE.bazel
- example/WORKSPACE.bazel
- example/buf.yaml
> chore(deps): example: upgrade buf to latest rules and tool runtime

- README.md
- docs/BUILD.bazel
- docs/stylelint.md
- example/.aspect/cli/config.yaml
- example/BUILD.bazel
- example/lint.sh
- example/package.json
- example/pnpm-lock.yaml
- example/src/BUILD.bazel
- example/src/hello.css
- example/stderr
- example/stylelint.config.mjs
- example/test/lint_test.bats
- example/tools/lint/BUILD.bazel
- example/tools/lint/linters.bzl
- lint/BUILD.bazel
- lint/stylelint.bzl
Fixes #340 
---
See added comment
> feat: stylelint

- docs/vale.md
- lint/mirror_vale.sh
- lint/vale_versions.bzl
> chore: mirror newest vale release

- example/MODULE.bazel
- example/WORKSPACE.bazel
- example/src/BUILD.bazel
- example/src/subdir/BUILD.bazel
- example/src/tsconfig.json
- example/test/BUILD.bazel
- lint/eslint.bzl
- lint/private/lint_aspect.bzl
> fix: don't run eslint with zero files to check

- docs/ruff.md
- lint/ruff.bzl
> chore: discourage use of select

- .github/workflows/release.yml
- .github/workflows/release_prep.sh
- .github/workflows/tag.yaml
Fixes #439
---
Used my test repo to create a release: https://github.com/alexeagle/test-auto-releases/actions
> fix: release artifacts with correct tag

- .aspect/workflows/config.yaml
- .github/workflows/ci.yaml
This reverts commit 5dd53a9534b8e7004e29a6d3addc3b085c2def23.
> Reapply "chore: switch remaining test to AW"

- .bazelrc
- lint/BUILD.bazel
Had to tag https://github.com/bazelbuild/bazel-central-registry/pull/4306 to get around this
> fix: green up BCR pushes

- docs/linting.md
- docs/ruff.md
- docs/shellcheck.md
- lint/ruff.bzl
- lint/shellcheck.bzl
Part of https://github.com/aspect-build/rules_lint/issues/551.
> Clarify how to use built-in linters

- format/BUILD.bazel
- lint/BUILD.bazel
See https://github.com/bazelbuild/bazel-skylib/issues/568
> fix: make correct bzl_library targets

- lint/spotbugs.bzl
Fixes aspect-build/rules_lint#579
> Fixes aspect-build/rules_lint#579 : fix SpotBugs classpath and inputs construction

- example/WORKSPACE.bazel
> chore: WORKSPACE needs rules_shell

- lint/lint.axl
> feat: demo a task
