aspect-build/rules_lint

BUILD.bazel, example/lint.sh, plugin.go
Fix the find command for macos
=> chore: mac portability

.github/workflows/ci.yaml, MODULE.bazel, example/MODULE.bazel
Also green up main CI by dropping windows for now
(it fails because we don't have an Aspect CLI windows binary yet)
=> chore: tighten up our bzlmod deps

example/test/BUILD.bazel, example/tools/lint.bzl, lint/eslint.bzl
It doesn't create the report when there are no warnings. Also account for the rule kind of ts_project in earlier releases of rules_ts
=> chore: workaround eslint bug

example/test/BUILD.bazel, example/test/no_violations.ts, lint/BUILD.bazel, lint/eslint.bzl, lint/eslint.workaround_17660.js
Changing to ctx.actions.run_shell caused the RUNFILES lookup logic to fail with bzlmod disabled.
(and we're missing test coverage)
added a "happy path" eslint_test target.
=> Better workaround for eslint bug

example/lint.sh, lint/README.md, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/lint_test.bzl, lint/pmd.bzl
Let's do this before the aspect-cli repo takes a dependency on the exact name.
---
=> chore: rename our output group to be more unique

example/lint.sh, lint/BUILD.bazel, lint/README.md, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/pmd.bzl, lint/private/BUILD.bazel, lint/private/lint_aspect.bzl
Makes it less likely the lint.sh shows wrong things.
=> refactor: rename our report outputs to be consistent

lint/BUILD.bazel, lint/eslint.bazel-formatter.js, lint/eslint.bzl
Demo:
```
example$ ./lint.sh src:all
INFO: Elapsed time: 0.954s, Critical Path: 0.88s
From /shared/cache/bazel/user_base/b6913b1339fd4037a680edabc6135c1d/execroot/__main__/bazel-out/k8-fastbuild/bin/src/unused_import.aspect_rules_lint.report:
src/unused_import.py:6:1: F401 'os' imported but unused
From /shared/cache/bazel/user_base/b6913b1339fd4037a680edabc6135c1d/execroot/__main__/bazel-out/k8-fastbuild/bin/src/foo.aspect_rules_lint.report:
src/Foo.java:9: FinalizeOverloaded:     Finalize methods should not be overloaded
From /shared/cache/bazel/user_base/b6913b1339fd4037a680edabc6135c1d/execroot/__main__/bazel-out/k8-fastbuild/bin/src/ts.aspect_rules_lint.report:
src/file.ts:2:7: Type string trivially inferred from a string literal, remove type annotation  [error from …
```
=> chore: fix eslint absolute paths

README.md, docs/BUILD.bazel, docs/shellcheck.md, example/.shellcheckrc, example/BUILD.bazel, example/WORKSPACE.bazel, example/WORKSPACE.bzlmod, example/lint.sh, example/src/BUILD.bazel, example/src/hello.sh, example/test/BUILD.bazel, example/tools/lint.bzl, lint/BUILD.bazel, lint/shellcheck.bzl
=> feat: add shellcheck

lint/ruff.bzl
The `example/`  repo fails to lint because the `ruff` binary it provides is a source file.
```
❮ bazel lint -- --java_runtime_version=remotejdk_11  src:all
ERROR: /home/plobsing/src/rules_lint/example/src/BUILD.bazel:31:11: in (an implicit dependency) attribute of //tools:lint.bzl%ruff[fail_on_violation="false"] aspect on sh_library rule //src:hello_shell: alias '//tools:ruff' referring to source file '@ruff_x86_64-unknown-linux-gnu//:ruff' is misplaced here (expected no files)
```
=> fix: allow ruff binary to be a source file

example/tools/BUILD
If the linter binaries aren't visible to targets under `src/`, linting fails with
```
❯ bazel lint -- --java_runtime_version=remotejdk_11  src:all
ERROR: /home/plobsing/src/rules_lint/example/src/BUILD.bazel:21:11: in //tools:lint.bzl%ruff[fail_on_violation="false"] aspect on py_library rule //src:unused_import: alias '//tools:ruff' referring to target '@ruff_x86_64-unknown-linux-gnu//:ruff' is not visible from target '//src:unused_import'. Check the visibility declaration of the former target if you think the dependency is legitimate. To set the visibility of that source file target, use the exports_files() function
ERROR: Analysis of aspects '[//tools:lint.bzl%eslint, //tools:lint.bzl%buf, //tools:lint.bzl%flake8, //tools:lint.bzl%pmd, //tools:lint.bzl%ruff] with parameters {} on …
```
=> fix: make lint tools visible to all subpackages of example repo

example/.bazeliskrc
`aspect/5.7.2` doesn't seem to include the `lint` command and `bazel lint src:all` fails with
```
Error: unknown command "lint" for "aspect"
```
This error is resolved by using version 5.8.5.
=> chore: reference latest aspect CLI version from .bazeliskrc

docs/formatting.md
As fix-mode does not return a non-zero status, it will not block submission when it detects formatting issues. Instead, it will reformat files but not stage them within `git`. The result is that users are not barred from submitting malformatted code; when they do, they'll have the fixes as unstaged changes in the files they just submitted.
Check-mode's behaviour will block submission, which is more similar to what `pre-commit.com` does and is probably what most users will expect.
=> docs: recommend check-mode for fallback pre-commit hook

lint/eslint.bzl, lint/flake8.bzl, lint/pmd.bzl, lint/ruff.bzl
These commonly contain an entry point or "main" which should be linted, but not contained in any *_library target srcs.
Fixes #40
=> feat: check srcs of *_binary targets in lint aspect walks

.github/workflows/release_prep.sh
We can't exclude examples because that's the bcr test module.
Oops!
=> chore: fix bcr publishing

format/private/format.sh, format/private/formatter_binary.bzl
There's a number of assumptions that the fix target is `//tools:format` when this might not be the case.
Adds a template string to the fix target in the failure error message on formatting.
---
Ensure formatting error fix target correctly reflects the name of the formatter binary target.
Run the formatter locally with a different target name.
=> fix: template the fix target string in failure error message

docs/ruff.md, example/src/hello copy.tf, example/src/subdir/BUILD.bazel, example/src/subdir/ruff.toml, example/src/subdir/unused_import.py, example/tools/lint.bzl, lint/ruff.bzl
Allows the common monorepo scenario where one application has to have a different configuration for whatever reason.
As documented at https://docs.astral.sh/ruff/configuration/#config-file-discovery the tool already knows how to select the right file for a given python source file.
=> feat: allow multiple ruff config files

example/lint.sh, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/pmd.bzl, lint/ruff.bzl, lint/shellcheck.bzl
Previously we always directed the tools output into a report file, but when you ask for the exit code to be used, this means the Bazel build fails without printing the result of the tool. Instead, all the logic related to directing output into the report file should only be used when exit code is ignored.
=> fix: in use_exit_code mode, print reports to stdio

format/private/format.sh
As per discussion here: https://github.com/astral-sh/ruff/discussions/5857#discussioncomment-6583943 pass `--force-exclude` when invoking `ruff format`
---
ruff format now respects exclude and extend-exclude directives in ruff.toml configuration files.
Add a directory path to an extend-exclude directive in ruff.toml and observe that the files in that directory are not formatted.
=> fix: Respect exclude when formatting with ruff

.bcr/metadata.template.json
I saw us making this change in other repos so it should be consistent. Maybe it also explains why I didn't get an email about rules_lint 0.6.1 not publishing a PR to BCR
=> chore: change maintainer to individual rather than team.

format/private/format.sh
With this approach deleted files are excluded, and untracked files are included.
Fixes https://github.com/aspect-build/rules_lint/issues/88
=> Exclude deleted files and include untracked ones from format

lint/ruff.bzl
* Adds Windows support for Ruff. I understand this repository doesn't support Windows as a whole yet, but this may prove useful to folks not using the CLI yet. 
Changes verified by running `bazel run //tools:ruff check` on Windows x64 machine, with appropriate alias configured.
=> Ruff Windows Support

MODULE.bazel, example/MODULE.bazel, example/MODULE.bazel.lock, example/WORKSPACE.bazel
This release stops using symbols that were removed in bazel-lib 2.0
=> fix: increase lower-bound of rules_js

lint/shellcheck.bzl
If the user has srcs in an sh_binary with shellcheck violations then it will a breaking change for them.
I don't think it deserves a major version bump tho.
- Manual testing; please provide instructions so we can reproduce: Add an sh_binary and see that their srcs are linted.
=> Enable shellcheck aspect for sh_binary

MODULE.bazel, README.md, docs/BUILD.bazel, docs/golangci-lint.md, example/.golangci.yaml, example/BUILD.bazel, example/MODULE.bazel, example/MODULE.bazel.lock, example/WORKSPACE.bazel, example/WORKSPACE.bzlmod, example/lint.sh, example/src/BUILD.bazel, example/src/hello.go, example/test/lint_test.bats, example/tools/BUILD, example/tools/lint.bzl, lint/BUILD.bazel, lint/golangci-lint.bzl
Fixes #82 
- Manual testing; please provide instructions so we can reproduce: `(cd example && ./lint.sh //...)`
Golang-ci lint relies on the go binary being in the PATH. I had to add rules_go as a dependency in the main repo for passing the toolchain type. I am not sure we can do this without that dependency.
=> Add golangci-lint as an aspect

README.md, docs/format.md, example/.clang-format, example/MODULE.bazel, example/MODULE.bazel.lock, example/WORKSPACE.bazel, example/src/BUILD.bazel, example/src/hello.cpp, example/tools/BUILD, format/private/format.sh, format/private/formatter_binary.bzl
---
Add support for formatting C/C++ code using clang-format.
Added example C++ file to show it is formatted by clang-format when format is run.
=> feat: Add clang-format for formatting C/C++

lint/golangci-lint.bzl
Without this, errors don't end up in the report file and are thus only displayed on the first run.
Suggested release note: golangci-lint: Fix capturing of output to report file from stdout rather than stderr
You can verify that this works better by repeatedly running "./lint.sh src:hello_go" in the example directory. Without this fix, only the first run yields the lint output and subsequent ones give empty output:
```console
dev-vm-db6l1 ~/src/rules_lint/example% ./lint.sh src:hello_go
INFO: Analyzed target //src:hello_go (242 packages loaded, 16606 targets configured).
INFO: From golangcilint src/golangcilint.hello_go.aspect_rules_lint.report:
../../bazel-source-roots/0/src/hello.go:13:2: SA1006: printf-style function with dynamic format string and no further arguments should use …
```
=> golangci-lint: Capture results from stdout rather than stderr

format/private/format.sh, format/test/format_test.bats
found a less-intrusive way to do this vs #120
Fixes #117 and #122.
---
- Passes tests in preliminary #126
=> fix filename pattern matching

lint/golangci-lint.bzl
A common pattern with go and blaze is to have go_library() targets that contain the source files and then trivial go_binary() targets that just wrap the matching library, without any other direct sources.
"golangci-lint run" fails on these binaries because it doesn't like an empty list of sources. It also generally seems pointless to run if we're not passing any files.
=> golangci-lint: Handle empty srcs list

.github/workflows/release_prep.sh
I noticed that the instructions in each release for using aspect-build/rules_lint with WORKSPACE don't include the dependency that it has on aspect-build/bazel-lib, and so if you follow the setup instructions literally you'll end up with errors when `bazel run`-ing your formatter target:
```
$ bazel run //tools:format
ERROR: Skipping '//tools:format': error loading package 'tools': at /private/var/tmp/_bazel_mattbrown/d7cfcf96ac70d7089c913ecc8b613cd1/external/aspect_rules_lint/format/defs.bzl:33:6: at /private/var/tmp/_bazel_mattbrown/d7cfcf96ac70d7089c913ecc8b613cd1/external/aspect_rules_lint/format/private/formatter_binary.bzl:3:6: Unable to find package for @@aspect_bazel_lib//lib:paths.bzl: The repository '@@aspect_bazel_lib' could not be resolved: Repository '@@aspect_bazel_lib' is …
```
=> fix undocumented dependency on aspect_bazel_lib for WORKSPACE users

format/private/format.sh
- Bug fix
- Breaking change (this change will force users to change their own code or config): No
- Relevant documentation has been updated: no relevant documentation
fixed the exit code of `multi_formatter_binary(...)` when `--mode check` is used with clang-format.
Manual testing:
- Modified example/hello.cpp to introduce a formatting error (e.g. remove a space after the left brace).
- Ran `bazel run //tools:format -- --mode check` and check the exit code is 1.
- Fixed the formatting error via `bazel run //tools:format`
- Ran `bazel run //tools:format -- --mode check` and checked the exit code is 0.
=> format: fix exit code of check when using clang-format

format/private/format.sh, format/test/format_test.bats
The tool we are using (terraform fmt) doesn't support all HCL file extensions. We should probably switch tools. I don't have time today so reducing scope from an 'HCL' language to a (locally-invented) 'Terraform' language with fewer file types
Fixes #141
---
`bazel run format --override_repository=aspect_rules_lint=$HOME/Projects/rules_lint` in aspect silo
=> fix(HCL): back out from formatting all HCL files

example/test/lint_test.bats, lint/eslint.bazel-formatter.js
The 'stylish' report is kinda hard to maintain a fork of it. I broke the errorformat parser by making our fork of stylish not quite the same.
In https://github.com/aspect-build/silo/pull/4540 I'm working on parsing the outputs of the linters, so we need to exactly match the known format. In theory the stylish report is better, but it has dependencies on chalk and strip-ansi that I'd rather not have to worry about here.
---
- Style (white-space, formatting, etc...)
=> fix(eslint): switch to compact report

docs/golangci-lint.md, lint/golangci-lint.bzl
This is what the //example workspace uses, and it's what I had to use to get this to work in our VideoAmp repo.
https://github.com/aspect-build/rules_lint/blob/ebe8678587abb1f9104abbfc6ca2ee1a8579b4aa/example/tools/lint.bzl#L59-L62
---
- This documentation matches the working version in //example
=> docs(golangci-lint): fix the target name

format/private/format.sh, format/test/format_test.bats
took a crack at parallelizing the formatter script, i think this works OK.
---
- Performance (a code change that improves performance)
- Patched this into another repository where rules_lint is in use, kicked the tires, made sure output was the same, it ran faster, and deviations were caught.
=> collapse common logic into run-format formula

format/repositories.bzl, lint/BUILD.bazel, lint/private/BUILD.bazel, lint/private/maybe.bzl, lint/shellcheck.bzl
Just some minor cleanup on the maybe patterns. In most places we don't have `name` so this makes the patterns here consistent with our other repos.
=> chore: cleanup maybe patterns

docs/vale.md, example/.vale.ini, example/BUILD.bazel, example/tools/lint.bzl, lint/mirror_vale.sh, lint/vale.bzl, lint/vale_versions.bzl
Thanks @jdkato for the fix in https://github.com/errata-ai/vale/commit/2139c4176a4d2e62d7dfb95dca24b96b9e8b7251 so we no longer need to tell users about copying their configuration file to be relative to the styles folder.
Note, to be less breaking I didn't remove the older Vale versions. Users who pinned to those and set their `StylesPath` should still work, as this newly added environment variable won't be referenced.
---
=> refactor: remove Vale workaround for StylesPath

.gitignore, MODULE.bazel, docs/format.md, docs/formatting.md, example/BUILD.bazel, example/tools/format/BUILD.bazel, format/BUILD.bazel, format/defs.bzl, format/private/BUILD.bazel, format/private/format.sh, format/private/formatter_binary.bzl, format/repositories.bzl, format/test/BUILD.bazel, format/test/format_test.bats
This has the side-effect of making a formatter binary per-language, which was one of our design review outcomes, since Aspect Workflows might want to be able to run them individually or in parallel.
FYI @keith since it's taking a dependency on your repo
Also now formats-in-parallel using the `jobs` attribute of `multirun`.
`multi_formatter_binary` is renamed to `format_multirun` and some attributes were renamed: 
- `sh` is now `shell`
- `protobuf` is now `protocol_buffer`.
=> Use multirun

docs/linting.md, example/lint.sh, lint/BUILD.bazel, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/golangci-lint.bzl, lint/lint_test.bzl, lint/pmd.bzl, lint/private/lint_aspect.bzl, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
The latter is a global namespace, and also leaked into a test where it shouldn't have been needed
---
`--aspects_parameters=fail_on_violation=true` must be replaced with `--@aspect_rules_lint//lint:fail_on_violation`
Ran `lint.sh --fail-on-violation //src:all` in the example.
=> refactor: use an explicit flag rather than attr_attribute

docs/buf.md, docs/eslint.md, docs/flake8.md, docs/golangci-lint.md, docs/lint_test.md, docs/linting.md, docs/pmd.md, docs/ruff.md, docs/shellcheck.md, docs/vale.md, example/tools/lint/linters.bzl, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/golangci-lint.bzl, lint/lint_test.bzl, lint/pmd.bzl, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
Linter factory symbols were renamed with a `lint_` prefix.
`multi_formatter_binary` was renamed to `format_multi_binary`.
=> Lint prefix

format/defs.bzl
Fixes a bug introduced in 0.14.0 like 'Markdown': key not found in dict
---
=> fix: guard lookups into DEFAULT_TOOL_LABELS

example/.bazeliskrc, example/WORKSPACE.bazel, example/WORKSPACE.bzlmod
Verified that the `bazel lint --fix` flow does the right thing.
=> chore: update aspect-cli to latest

MODULE.bazel, docs/format.md, docs/formatting.md, format/BUILD.bazel, format/defs.bzl, format/private/BUILD.bazel, format/private/format.sh, format/private/formatter_binary.bzl, format/repositories.bzl, format/test/BUILD.bazel, format/test/format_test.bats
This reverts commit 1fbcfee669b0b546071a85fb48e927dc3fe33662.
The broken feature for passing filename arguments is fixed in https://github.com/keith/rules_multirun/releases/tag/0.9.0
---
=> Revert "Revert "Use multirun (#160)" (#171)"

format/repositories.bzl
Includes https://github.com/theoremlp/rules_multitool/pull/21 which we want in aspect silo
Note, it's not necessary to increase the lower bound for bzlmod users, as that API already allowed multiple lockfiles.
---
- Chore (any other change that doesn't affect source or test files, such as configuration)
Now requires bazel_features as a transitive WORKSPACE dep of rules_multitool.
=> chore: upgrade rules_multitool for WORKSPACE users

format/defs.bzl
fixes #97
---
Introduced .js file format violation in silo, it now continues on to check formatting of other languages
=> fix(format): don't bail check mode on first error

docs/shellcheck.md, lint/shellcheck.bzl
- Relevant documentation has been updated? We don't document which linters have fixes auto-applied, but I'm not sure that we should, since it will be hard to keep that updated.
```
example% ./lint.sh --fix src:hello_shell
From bazel-out/darwin_arm64-fastbuild/bin/src/shellcheck.hello_shell.aspect_rules_lint.report:
In src/hello.sh line 3:
[ -z $THING ] && echo "hello world"
^----^ SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean: 
[ -z "$THING" ] && echo "hello world"
For more information:
https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
patching file …
```
=> feat: shellcheck apply fixes

docs/format.md, format/defs.bzl
fixes #197
New behavior:
```
$ bazel run format src/hello.sh
INFO: Analyzed target //:format (2 packages loaded, 26 targets configured).
INFO: Found 1 target...
Target //tools/format:format up-to-date:
bazel-bin/tools/format/format.bash
INFO: Elapsed time: 0.193s, Critical Path: 0.01s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/tools/format/format.bash src/hello.sh
Formatted Shell in 0m0.004s
alex@a:~/Projects/rules_lint/example$ 2>/dev/null bazel run format README.md 
Formatted Markdown in 0m0.346s
alex@a:~/Projects/rules_lint/example$ bazel run format README.md
INFO: Analyzed target //:format (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/format:format up-to-date: …
```
=> feat(format): expose print_command and change default to False

MODULE.bazel, docs/golangci-lint.md, docs/shellcheck.md, example/.aspect/cli/config.yaml, example/MODULE.bazel, example/WORKSPACE.bazel, example/WORKSPACE.bzlmod, example/tools/lint/BUILD.bazel, example/tools/lint/linters.bzl, lint/BUILD.bazel, lint/golangci-lint.bzl, lint/multitool.lock.json, lint/shellcheck.bzl
Continues the work from setting up formatters this way.
Includes an upgrade of shellcheck to the latest release.
1. Remove any `fetch_shellcheck` or `fetch-golangci_lint` calls.
2. Replace references of a local shellcheck binary with `@multitool//tools/shellcheck` and delete the local binary
3. Replace references of golangci-lint binary with `@multitool//tools/golangci-lint` and delete local binary or alias
=> refactor: bring linters under rules_multitool

format/private/formatter_binary.bzl
---
Pass the `--apply-ignore` flag the shfmt when checking to see if files are already formatted.
shfmt will now respect ignores in .editorconfig even in check mode.
I didn't see any existing tests for check mode.
=> fix: pass flag to shfmt to ignore passed files in check mode

docs/ktlint.md, lint/BUILD.bazel, lint/ktlint.bzl
Follow-up on https://github.com/aspect-build/rules_lint/pull/215, this adds support for the `--ruleset` argument with `ktlint` https://pinterest.github.io/ktlint/1.2.1/install/cli/#rule-sets
For most people, the standard rulesets may suffice. However, in large codebases it's common to write your own custom rules and use them on top of standard rules. This adds support for it by updating the `ktlint` aspect.
This is not a breaking change and existing test cases should pass. I'd like to add testcases for this code path, but that'd require adding a custom ruleset dependency here. There's no popular OSS custom rulesets and not sure it has to live here (although I'd be happy to add). I've tested this against our custom rules and it seems to work as expected.
=> ktlint: Add option to use custom rulesets

lint/ruff.bzl
`lint_ruff_aspect` currently uses `allow_single_file` for the executable `_ruff` aspect. This is an unnecessary restriction: since we don't use `ctx.file._ruff` (only `ctx.executable._ruff`), we are needlessly blocking the use of rule targets that produce multiple default output files in addition to the necessary executable file.
This is a problem, for example, when trying to use an `sh_binary` target as `binary` for `lint_ruff_aspect`, since `sh_binary` produces all the srcs scripts as well as a generated entrypoint. Currently, `lint_ruff_aspect` refuses this, as it's not a single-file target. But it shouldn't matter, because `sh_binary` does produce an executable file for use as `ctx.executable._ruff`.
I haven't added a test for this, since testing multiple different `lint_ruff_aspect`s …
=> fix: use `allow_files` in `lint_ruff_aspect`

example/lint.sh
Linting is generally orthogonal to other "validation" actions - users want to see lint reports even if some validation actions are in a failing state.
See https://github.com/aspect-build/rules_ts/pull/574#issuecomment-2073632879
---
Ran `lint.sh`.
=> fix: lint.sh pass norun_validations

docs/eslint.md, docs/ruff.md, example/lint.sh, example/src/file.ts, example/src/hello.sh, example/src/unused_import.py, lint/BUILD.bazel, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/ktlint.bzl, lint/pmd.bzl, lint/private/BUILD.bazel, lint/private/lint_aspect.bzl, lint/private/patcher.mjs, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
ruff and eslint both have the ability to produce the report of unfixable violations in the same execution that applies fixes.
We can use this to avoid having a second action run under `--fix`
For eslint in particular, this is a required performance improvement.
---
- Breaking change (forces users to change their own code or config): yes, slightly
To produce fixes, users must now pass the `--@aspect_rules_lint//lint:fix` flag.
The `lint.sh` helper script has been updated accordingly, and will need to be re-vendored into your repository.
```
$ ./lint.sh --fix --dry-run …
```
=> refactor: produce report and exit code in the same action with fixes

format/defs.bzl
I use rules_lint via a macro in my own company rules--this allows it to work that way via bzlmod.
---
Create a macro containing `format_multirun` and `format_test` in one repository/module, and call that macro from the root module.
=> Use explicit labels to allow using from other repositories

format/private/format.sh, format/test/ls-files_test.sh
As reported in #233
Fixes #233 
---
Without this change, users would have seen errors, so this is indeed something visible to users as a bug fix.
I only tested this locally.
- Automated tests
```starlark
format_multirun(
name = "format",
yaml = "@multitool//tools/yamlfmt",
... # everything else as False
)
```
Create a git repo with two folders: `foo`, `bar`, each with an yaml file `foo.yaml` and `bar.yaml`.
```shell
$ git sparse-checkout init
$ git sparse-checkout add foo
$ bazel run //path/to/the/format:target
```
Yaml formatter would complain file not found or similar without this fix.
=> fix(format): Skip files with skip-worktree bit set

docs/format.md, format/defs.bzl, format/private/format.sh, format/test/ls-files_test.sh
Previously, format.sh only took git attributes
into account if it was passed no arguments.
For both code paths if the last argument passed is `--disable_git_attribute_checks` filtering based on .gitattributes will be disabled.
---
- Searched for relevant documentation and updated as needed: no
- Breaking change (forces users to change their own code or config): yes
=> feat: format.sh has same behavior with arguments

format/private/format.sh
Fixes #230
---
When `format.check` fails, it now prints a command that includes the arguments it was passed.
```
alexeagle@MacBook-Pro-79 example % bazel run tools/format:format.check src/hello.scss src/hello.rs              
Checking formatting...
[warn] src/hello.scss
[warn] Code style issues found in the above file. Forgot to run Prettier?
FAILED: A formatter tool exited with code 1
Try running 'bazel run //tools/format:format_CSS_with_prettier src/hello.scss src/hello.rs' to fix this.
Formatted Rust in 0m0.029s
Error: bazel exited with exit …
```
=> feat: print better command to fix format check fails

example/BUILD.bazel, example/eslint.config.mjs, example/package.json, example/pnpm-lock.yaml, example/src/BUILD.bazel, example/src/subdir/BUILD.bazel, example/src/subdir/test.ts, example/src/tsconfig.json, example/tools/lint/linters.bzl, format/test/format_test.bats, lint/eslint.bzl
```
example % bazel lint src/subdir:ts
WARNING: Option 'experimental_remote_download_regex' is deprecated: Use --remote_download_regex instead
WARNING: Option 'experimental_remote_download_regex' is deprecated: Use --remote_download_regex instead
INFO: Analyzed target //src/subdir:ts (0 packages loaded, 0 targets configured).
[4 / 5] ESLint src/subdir/ESLint.ts.aspect_rules_lint.report; 0s darwin-sandbox
From //src/subdir:ts:
1
From //src/subdir:ts:
src/subdir/test.ts: line 3, col 1, Warning - Imports should be sorted alphabetically. (sort-imports)
src/subdir/test.ts: line 3, col 10, Error - 'IncomingHttpHeaders' is defined but never used. (@typescript-eslint/no-unused-vars)
src/subdir/test.ts: line 7, col 28, Error - 'any' overrides all other types in this union type. …
```
=> fix(example): demonstrate use of type definitions in eslint aspect

example/test/lint_test.bats, lint/private/lint_aspect.bzl
Pulling the mnemonic out of the filename is difficult with the current naming:
```
path/to/target/mnemonic.label/with/slashes.aspect_rules_lint.report
```
This PR changes it to
```
path/to/target/label/with/slashes.aspect_rules_lint.mnemonic.report
```
so downstream tools can assume the file ends with `.mnemonic.report`
(same for `.exit_code` and `.patch` suffixes)
=> fix: move mnemonic to after label in report, exit_code and patch output filename

example/MODULE.bazel
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
=> chore: bump example to bazel-lib 2.7.5

docs/format.md, format/defs.bzl
Requested by https://github.com/aspect-build/rules_lint/pull/251#discussion_r1619200206
---
=> docs: clarify what's not recommended

format/private/format.sh, format/test/ls-files_test.sh
this fixes #261, which is caused by the branch in this code when `disable_git_attribute_checks` is set returning the full list of files rather than echoing them one at a time as the other branch does:
https://github.com/aspect-build/rules_lint/blob/30c5c399b07f0327b9d4ffaf67370d7be7e79285/format/private/format.sh#L129-L142
- incorrect existing test fixed
I've created <https://github.com/mattnworb/aspect-lint-rc1-repro> to reproduce #261, and the branch <https://github.com/mattnworb/aspect-lint-rc1-repro/tree/fix-disable_git_attribute_checks> tests this patch.
It would be a good idea to add a test case to this repo for this sort of thing, to prevent it from happening in the first place, but I have not yet done this.
=> fix(format): "File name too long" when using --disable_git_attribute_checks

docs/format.md, format/defs.bzl, format/test/BUILD.bazel
We recently upgraded a repo containing ~1500 Java source files from `0.21.0` to `v1.0.0-rc1` and noticed that running `format_multirun()` over the whole codebase without any arguments (e.g. `bazel run format`) was significantly slower than before.
For example, we would see execution times like
```
> time bazel run //:format
...
Formatted Python in 0m0.062s
Formatted Starlark in 0m0.087s
Formatted Java in 0m3.535s
Formatted Go in 0m0.039s
Formatted Shell in 0m0.051s
Formatted Protocol Buffer in 0m1.878s
Formatted YAML in 0m0.154s
real    0m22.364s
user    0m41.983s
sys     0m6.982s
```
note that these numbers don't add up - in particular, a large amount of the 22s `real` time was waiting for the Java formatter.
Before the upgrade, we'd see Java formatter times like:
```
> time bazel run …
```
=> feat: add format_multirun() attribute to disable slow gitattribute checks

example/lint.sh, example/test/lint_test.bats, lint/README.md, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/ktlint.bzl, lint/pmd.bzl, lint/private/lint_aspect.bzl, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
Standardize the mnemonic for linters in this repository to `AspectRulesLintFoobar` so that we don't collide with other mnemonics and so that downstream tools that post-process generated report, patch and exit_code files can reliably determine the linter type using this convention.
=> refactor: introduce mnemonic convention for rules_lint linters

.github/workflows/ci.yaml, example/.bazelrc, example/MODULE.bazel, example/WORKSPACE.bazel
Avoids compiling protoc from source in the example. Also cleanup other BCR dependency versions.
---
=> chore(example): enable proto toolchain resolution

docs/eslint.md, lint/eslint.bzl
Addresses small miss in the documentation. (#275)
Updates to the docstring will assist in setup tasks for new users of `rules_lint`.
---
=> Correct docstring for eslint (#275)

format/private/format.sh, format/test/ls-files_test.sh
Now rather than calling grep N times where N is
the number of files to be formatted, we call grep
0 times and simply iterate through the array of
lines outputted by git check-attr
---
Git attribute based ignoring files performance increase!
=> feat: Optimize the git ignore checks

docs/ktlint.md, lint/eslint.bzl, lint/flake8.bzl, lint/ktlint.bzl, lint/pmd.bzl, lint/private/lint_aspect.bzl, lint/ruff.bzl, lint/shellcheck.bzl
Many tools fail if we don't provide any input files. Skipping the actions seems like the cleanest solution.
The other alternative is to always generate an empty report and a status code file with 0, but that seems unnecessary. On the other hand, it would make the tests cleaner. 
@alexeagle what do you think?
---
I am planning to update the tests in lint_tests, but I wanna make sure this is the right approach first.
=> Only run aspect actions when input files provided

README.md, docs/format.md, example/src/hello.cu, example/tools/format/BUILD.bazel, format/private/filter.jq, format/private/format.sh, format/private/formatter_binary.bzl, format/test/BUILD.bazel, format/test/format_test.bats
---
Adds support for formatting cuda files by passing clang_format target to the cuda attribute of format_multirun.
=> feat: Add Cuda format support

lint/clang_tidy_wrapper.bash
Use env to find the path to bash - don't assume bash is located in /usr/bin
=> Update clang_tidy_wrapper.bash shebang

docs/clang-tidy.md, lint/clang_tidy.bzl
Fixes parameter shadowing in the _safe_flags macro.
---
- Searched for relevant documentation and updated as needed: yes/no
Pass C++ toolchain and copt flags to clang-tidy.
=> Fix safe_flag parsing in clang_tidy.bzl

docs/ruff.md, lint/BUILD.bazel, lint/mirror_ruff.sh, lint/ruff.bzl, lint/ruff_versions.bzl
they made breaking changes to their tagging and artifact naming schemes:
https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#050
https://github.com/astral-sh/ruff/discussions/12078
=> chore: fix ruff mirroring

docs/vale.md, lint/vale_versions.bzl
Our automation isn't complete so this doesn't run on GitHub Actions.
=> chore: mirror latest vale release

lint/ruff.bzl
=> fix: ruff 0.5.0 windows release doesn't nest a folder

docs/buf.md, docs/eslint.md, docs/flake8.md, docs/ktlint.md, docs/pmd.md, docs/ruff.md, docs/shellcheck.md, docs/vale.md, lint/buf.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/ktlint.bzl, lint/pmd.bzl, lint/private/lint_aspect.bzl, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
This lets users adapt for situations where they have a custom rule, for example.
=> feat: linter aspect factories allow customizing rule kinds

README.md, docs/format.md, example/src/hello.graphql, example/tools/format/BUILD.bazel, format/private/filter.jq, format/private/format.sh, format/private/formatter_binary.bzl, format/test/BUILD.bazel, format/test/format_test.bats
Prettier supports GraphQL natively. The file extensions are registered with the formatter and a basic format test is added.
---
- Suggested release notes appear below: 
GraphQL is added as a language to `format_multirun` to opt into formatting with prettier.
An example hello.graphql file was added which is fixed when running `bazel run format` from `examples/`. There is also a unit test that prettier is invoked with graphql files.
=> feat: add GraphQL format support (#319)

lint/eslint.bzl
The LintOptionsInfo provider tracks a debug setting that should enable debug level logging for linters that support it. A TODO was left in the eslint.bzl noting the missing integration. This is now added by conditionally adding the --debug flag to the eslint args.
---
This fixes integration via `--@aspect_rules_lint//lint:debug`
I don't believe any existing automated cases check the debug bool. I did confirm that when enabled in examples it writes the logs out to STDOUT.
=> fix: connect eslint --debug

docs/eslint.md, docs/flake8.md, docs/ktlint.md, docs/pmd.md, docs/ruff.md, docs/vale.md, example/test/lint_test.bats, lint/BUILD.bazel, lint/eslint.bzl, lint/flake8.bzl, lint/ktlint.bzl, lint/pmd.bzl, lint/private/lint_aspect.bzl, lint/ruff.bzl, lint/shellcheck.bzl, lint/vale.bzl
Demo with
```shell
example % ./lint.sh src:ts src:hello_kt src:md src:hello_shell src:unused_import src:foo
```
---
The human-readable report now includes colored output. Set `--no@aspect_rules_lint//lint:color` to inhibit this.
=> feat: color the human-readable outputs

example/lint.sh
It was broken because it used the wrong file as the patch. See https://github.com/aspect-build/rules_lint/commit/7a14cfdee5f97ae6ad9f3fda66fa83f4094b79a6#r144358642
Note, this might mean we should add some automated testing for `lint.sh` - but I'd rather spend time on the `aspect lint` command.
---
```
example % ./lint.sh --fix --dry-run src:ts     
From bazel-out/darwin_arm64-fastbuild/bin/src/ts.AspectRulesLintESLint.out:
/private/var/folders/8n/7cfngjb106sgwb8mr1tytx700000gn/T/rules_lint_patcher-pgLeXz/_main/bazel-out/darwin_arm64-fastbuild/bin/src/file.ts
7:1  error  Unnecessary try/catch wrapper  no-useless-catch
✖ 1 problem (1 error, 0 warnings)
From bazel-out/darwin_arm64-fastbuild/bin/src/ts.AspectRulesLintESLint.pa …
```
=> fix: lint.sh script --fix flag

lint/BUILD.bazel, lint/eslint.bzl, lint/eslint.compact-formatter.js, lint/eslint.stylish-formatter.js
Thanks @gregmagolan for walking me through the technique required.
---
```
% ./lint.sh src:ts      
From bazel-out/darwin_arm64-fastbuild/bin/src/ts.AspectRulesLintESLint.out:
src/file.ts
2:7  error  Type string trivially inferred from a string literal, remove type annotation  @typescript-eslint/no-inferrable-types
7:1  error  Unnecessary try/catch wrapper                                                 no-useless-catch
✖ 2 problems (2 errors, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
=> fix(eslint): print relative paths in stylish output

example/package.json, example/pnpm-lock.yaml, example/src/BUILD.bazel, example/src/file-dep.ts, example/src/file.ts, example/test/lint_test.bats, format/test/format_test.bats, lint/eslint.bzl
typescript-eslint requires type declarations for imports when evaluating type checked lint rules. These declarations are included as inputs to the eslint action and a regression test under examples/ is included to confirm that types from both npm packages and locally imported sources are resolved.
- Searched for relevant documentation and updated as needed: no
- Breaking change (forces users to change their own code or config): yes
Fixes #335
=> fix: include transitive type declarations with eslint

.pre-commit-config.yaml, docs/stylelint.md, example/src/cpp/lib/get/.clang-tidy, example/src/cpp/lib/get/get-time.h, lint/stylelint.bzl
Also add spell checker like we have now in bazel-lib
---
=> chore(docs): fix eslint copy-pasta

.github/workflows/release_prep.sh
Now it matches the version in MODULE.bazel.
Fixes #351
=> chore: update bazel-lib version in WORKSPACE snippet

lint/clang_tidy.bzl
Previously cxxopts were used even if the source was a C file.  Now cxxopts and copts are passed correctly to clang-tidy depending on the file type.
---
Include a C++ only flag in `.bazelrc` e.g. ` build --cxxopt="-std=c++17"` and  lint a C target.
=> Remove cxxopt flags when linting C sources.

docs/format.md, example/src/BUILD.bazel, example/src/hello.c, example/tools/format/BUILD.bazel, format/private/format.sh, format/private/formatter_binary.bzl
This adds `clang-format` support for C files `*.c`.  `clang-tidy` support already works correctly for `cc_*` targets with C sources.
It wasn't clear the best way to add `*.c` to `format.sh` given how it seems the output of `mirror_linguist_languages.sh` is manually copied over.
---
- Given how `cc_*` targets silently handle C and C++ users likely already expect C support.
- Add support for formatting C files.
=> Add C example and file extension.

lint/private/lint_aspect.bzl
Fixes #346
Note, I haven't added a test here since I didn't figure out how to repro yet. Would take a few brain cycles, maybe worth doing if the reviewer wants it.
=> fix: filter out 'external' sources from linting

.github/workflows/release_prep.sh, MODULE.bazel
We used a single_version_override locally which makes it hard to repro what users see. Note that the example was already on 2.7.7, this just lines them up.
Fixes #351
=> chore(deps): bump bazel-lib minimum

lint/private/lint_aspect.bzl
#331 introduced a bug where the noop lint fails if running with fail on validation. 
If we have a lint aspect that has no files to lint and run with fail-on-validation the exit_code file will be set to None. Which is why we need to check that its not None before trying to access its path.
Relevant error
```
Traceback (most recent call last):
File "/home/tokongs/.cache/bazel/_bazel_tokongs/51d0d670cf09bb319bf1151bdc73a969/external/aspect_rules_lint~/lint/ruff.bzl", line 165, column 25, in _ruff_aspect_impl
noop_lint_action(ctx, outputs)
File "/home/tokongs/.cache/bazel/_bazel_tokongs/51d0d670cf09bb319bf1151bdc73a969/external/aspect_rules_lint~/lint/private/lint_aspect.bzl", line 144, column 65, in noop_lint_action
commands.append("echo 0 > {}".format(outputs.human.exit_code.path))
Error: …
```
=> Fix crash caused by fail-on-violation and no lintable files in target

.github/workflows/ci.yaml
0.6.0 starts using the Bazel 7 built-in `starlark_doc_extract` rule which our docsite expects
---
None; docs only
=> chore(deps): update stardoc

.github/workflows/ci.yaml
Reverts aspect-build/rules_lint#363
I did something wrong in a rebase and lost the stardoc version bump.
=> Revert "chore(deps): update stardoc"

.github/workflows/ci.yaml, MODULE.bazel, docs/buf.md, docs/clang-tidy.md, docs/eslint.md, docs/flake8.md, docs/format.md, docs/ktlint.md, docs/lint_test.md, docs/pmd.md, docs/ruff.md, docs/shellcheck.md, docs/stylelint.md, docs/vale.md
It produces better markdown output (e.g. no more HTML for code blocks) and includes `load` statements on examples.
Also uses `native.starlark_doc_extract`, which Aspect docsite now requires.
---
Note, I had to change our testing matrix, since newer stardoc module has a hard requirement in BCR of Bazel 7 or greater.
=> chore: update stardoc

format/private/formatter_binary.bzl, format/test/format_test.bats
https://github.com/aspect-build/rules_lint/issues/371
This is a similar solution how rules_lint handles ruff with the `--force-exclude` flag.
---
Follow the reproduction instructions in my example repo before and after this change: https://github.com/vinnybod/bazel_java_example/tree/rules_lint_config
After this change, it only formats the file that is expected to be formatted.
=> Add --respect-project-filters to scalafmt

README.md, docs/BUILD.bazel, docs/checkstyle.md, example/.aspect/cli/config.yaml, example/BUILD.bazel, example/WORKSPACE.bazel, example/WORKSPACE.bzlmod, example/checkstyle-suppressions.xml, example/checkstyle.xml, example/src/BUILD.bazel, example/src/Bar.java, example/test/BUILD.bazel, example/tools/lint/BUILD.bazel, example/tools/lint/linters.bzl, format/test/format_test.bats, lint/BUILD.bazel, lint/checkstyle.bzl
Adds a Checkstyle linter for Java. I pretty much copied the pmd implementation, so let me know if anything is out of place. I updated the examples and in my [own repo](https://github.com/vinnybod/bazel_java_example/tree/rules_lint_checkstyle).
---
Run the checkstyle linter in the examples repo. See that it raises linting issues. Note that the unused import should not raise an issue because it is excluded in suppressions.xml
=> Add a checkstyle linter

lint/private/lint_aspect.bzl
Fixes failure when requesting machine outputs if --@aspect_rules_lint//lint:fail_on_violation is set
```
```
=> fix: handle empty exit_code File when fail_on_violation is set

docs/formatting.md, format/private/format.sh, format/test/ls-files_test.sh
Prior to this change, if one of the git attributes used to disable format checks was set to a value
of `true`, it was still formatted since the only
valid syntax was setting the attribute without
any value.
After this change the attributes can be used without a value or with the value of `true`
Fixes https://github.com/aspect-build/rules_lint/issues/383
---
Git attributes for disabling format checks now support both unset values and `true`. This allows for more flexible configuration when excluding files from formatting.
=> fix(format): Allow git-attributes to be set to true

docs/linting.md
Fix minor typo in linting.md leading to a broken link to linters.bzl.
=> Fix broken link in linting.md

format/private/formatter_binary.bzl
- when using ruff as formatter and during check, a diff will be displayed in case of files to format
=> Use --diff when running ruff as check

format/private/format.sh
Add support for '@file' syntax to read format targets from a file Implement batch processing to handle large numbers of files Maintain compatibility with direct command-line arguments
This change allows the format command to process an arbitrarily large number of files by reading targets from a file, bypassing OS command line length limits. It addresses issues with pre-commit hooks and other tooling when formatting many files at once.
Note: This introduces a limitation where files starting with '@' cannot be directly specified as format targets. Users must use the full file path for such files.
Closes #387
---
- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes
- Suggested release notes appear below: …
=> fix: support file list input for format command to bypass OS limits

docs/stylelint.md, example/BUILD.bazel, example/package.json, example/pnpm-lock.yaml, example/stylelint.config.mjs, lint/BUILD.bazel, lint/stylelint.bzl
If the stylelint config is declared via js_library and has a dependency on other sources or npm packages, these dependencies are now included in the linting action.
---
yes, this fixes a bug in what is a standard pattern
- The existing test case is extended to have a dependency on a npm package in the config
=> fix: Include stylelint config deps (#394)

.github/workflows/ci.yaml, MODULE.bazel, docs/BUILD.bazel, docs/format.md
Currently we only test on Bazel 7. Bazel 8 is due next week and this ruleset should be high-polish since I have a bazelcon talk on it.
=> feat: start testing on Bazel 8

.github/workflows/ci.yaml, MODULE.bazel, docs/BUILD.bazel, docs/format.md
Reverts aspect-build/rules_lint#401
It broke main. I should have pinned the new reusable workflow at a commit instead of using a branch.
=> Revert "feat: start testing on Bazel 8"

docs/eslint.md, lint/eslint.bzl
=> docs(eslint): upgrade ts_project macro notes

docs/format.md, example/BUILD.bazel, example/MODULE.bazel, example/package.json, example/pnpm-lock.yaml, example/prettier.config.cjs, example/tools/format/BUILD.bazel, format/defs.bzl
It didn't work correctly because `bazel run` does not use a sandbox, so prettier finds the config file in the source tree and then finds node_modules in the source tree. Instead the plugin loading should be explicit, and point prettier at the right config file
Fixes #176
=> fix: remove clumsy prettier plugin hoisting

lint/clang_tidy.bzl
Updated the compilation_context used by clang-tidy lint actions to include implementation_deps so that any headers that are made available via implementation_deps targets are now visible to clang-tidy.
---
- Searched for relevant documentation and updated as needed: no
clang-tidy can now see headers provided by `implementation_deps`
Create a C++ target that has an implementation_dep that provides a header file; try to include the header and clang_tidy will fail to find it without this change.
=> fix: Add implementation_deps to the compilation_context used for clang-tidy

example/tools/lint/BUILD.bazel, lint/pmd.bzl
There is a minor breaking change to the CLI args, so users have to upgrade along with rules_lint. If they use our fetch_pmd helper this works automatically.
However they also must update the java_binary main_class attribute.
Fixes #418
=> chore: upgrade PMD to version 7

.github/workflows/release.yml, .github/workflows/tag.yaml, CONTRIBUTING.md
Quality of life improvement for maintainers.
Tested this out here: https://github.com/alexeagle/test-auto-releases
---
=> chore: setup tagging in GHA

format/defs.bzl, format/private/format.sh, format/test/ls-files_test.sh
This fixes the ability to run `bazel run //:format -- <filenames>` with git attribute parsing disabled.
`format.sh` expected this flag to be the last argument, however when running with `rules_multirun` all arguments passed at the end of `bazel run` get appended to the `args`. So, the flag that was expected to be last was no longer last, and it re-enabled gitattribute parsing and caused an issue with `find` not expecting this flag.
This patch makes it an environment variable, like all other information that's passed to the format.sh script.
-----
The bug:
```
❯ bazel run //:format -- defs.bzl
...
INFO: Running command line: bazel-bin/format.bash defs.bzl
...
find: illegal option -- -
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path …
```
=> Pass disable_git_attribute_checks via env instead

lint/clang_tidy.bzl, lint/eslint.bzl, lint/stylelint.bzl
=> perf: avoid use of depset.to_list

.github/workflows/tag.yaml
We could easily make an oversight in reviewing a PR commit message and release a new semver major without meaning to
See https://github.com/smlx/ccv/issues/161
---
=> fix: don't auto-release majors

example/package.json, example/pnpm-lock.yaml, lint/BUILD.bazel, lint/js/eslint.stylish-formatter.js
They changed some dependencies. One of them we can just drop with their newer code that works with older eslint releases. The other (text-table) needs to be vendored so it works with both versions, both older ones which expected a third-party package, and newer ones that don't depend on that package.
Fixes #434
---
=> chore: re-vendor newer eslint stylish formatter

lint/BUILD.bazel, lint/js/BUILD.bazel, lint/js/stylelint.compactFormatter.mjs, lint/stylelint.bzl
Patch the stylelint compact formatter so that it outputs relative paths. This is needed as by default we were getting paths that included the bazel-out directory
---
- Searched for relevant documentation and updated as needed: no
Stylelint will now output relative, non-bazel paths
I ran this using the aspect CLI and produced the following result:
```
Patch for //src:css from linter mnemonic AspectRulesLintStylelint
Lint results for //src:css:
src/hello.css: line 11, col 5, error - Unexpected empty block (block-no-empty)
src/hello.css: line 16, col 3, error - Unexpected …
```
=> fix: Use relative paths with stylelint

format/private/format.sh, format/test/format_test.bats
**buf** seems to be painfully slow when running with the positional argument `<source>`.
(I opened https://github.com/bufbuild/buf/issues/3593 for them to track but 🤷 if they will provide anything meaningful).
The downside of this repo is that `--path` is a very **buf** specific option.
I couldn't see how to pipe args from the tool -> _format.sh_ but that might be an improvement later.
You can see the discrepancy here (tested with latest buf release 1.41.0): 
**original**
```shell
> time bazel run //tools/format:format_Protocol_Buffer_with_buf
INFO: Invocation ID: 7458a050-c88b-4fce-a3da-11c781947b98
INFO: Analyzed target //tools/format:format_Protocol_Buffer_with_buf (69 packages loaded, 328 targets configured).
INFO: Found 1 target...
Target …
```
=> Make buf format fast

.github/workflows/release.yml
Last release is broken, somehow it didn't find an argument to pass to release_prep.sh
https://github.com/aspect-build/rules_lint/actions/runs/12933556117
Grabs this delta https://github.com/bazel-contrib/.github/compare/master...alexeagle-patch-3
Have to land it on main in order to test
=> fix: try to unstick release

.github/workflows/release_prep.sh
caused `.github/workflows/release_prep.sh: line 14: WORKSPACE.bazel: command not found`
=> fix: release snippet missing escaping

.bcr/presubmit.yml
We depend on rules_jvm_external which no longer supports it.
error is like
```
(03:51:09) ERROR: file:///workdir/modules/rules_jvm_external/6.5/MODULE.bazel:101:13: name 'use_repo_rule' is not defined
(03:51:09) ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rules_jvm_external@6.5: error executing MODULE.bazel file for rules_jvm_external@6.5
```
had to make this change previously as part of https://github.com/bazelbuild/bazel-central-registry/pull/3452
=> fix: drop Bazel 6 support

example/.ruff.toml, example/test/BUILD.bazel, example/test/excluded.py, lint/ruff.bzl
Without this flag, it will lint files that are excluded by the config file since we pass explicit filename arguments
=> fix(ruff): honor exclusions when linting

README.md, docs/format.md, example/package.json, example/src/hello.xml, example/tools/format/BUILD.bazel, format/private/format.sh, format/private/formatter_binary.bzl, format/test/BUILD.bazel, format/test/format_test.bats
Added XML as a supported formatter and make it use prettier by default. I am not interested in using prettier myself but it's already configured so I might as well. 
- Tested on my own repo with a custom xml formatter.  
- Commit is here but i do not expect you to run it yourself https://github.com/b0inbot/tools/commit/0b13ed07555c8e8081055cd41dd30c8cc9bcb3d6
- unable to test via bazel run format within the example/ folder (Error running code complaining about libcrypt so.) Hoping CI/CD within ubuntu can run the test case.
- test folder does work:
```
$ pwd …
```
=> feat: add XML format via prettier

example/BUILD.bazel, example/checkstyle-suppressions.xml, example/checkstyle.xml, example/ktlint-baseline.xml, example/pmd.xml, example/pnpm-lock.yaml, example/prettier.config.cjs, example/spotbugs-exclude.xml
Follow-up to #474 where the example didn't work
=> fix: make XML formatter functional in example

lint/lint_test.bzl
As `@bazel_tools//tools/bash/runfiles` is now an alias to `@rules_shell//shell/runfiles` with Bazel@HEAD, consumers must properly merge all its runfiles rather than assuming that the `sh_library` target just consists of a single file.
Work towards https://github.com/bazelbuild/examples/pull/557#issuecomment-2677865427
=> Merge all runfiles of `@bazel_tools//tools/bash/runfiles`

README.md, docs/format.md, example/BUILD.bazel, example/package.json, example/pnpm-lock.yaml, example/prettier.config.cjs, example/src/Bar.java, example/src/Foo.java, example/src/hello.feature, example/tools/format/BUILD.bazel, format/private/filter.jq, format/private/format.sh, format/private/formatter_binary.bzl, format/test/BUILD.bazel, format/test/format_test.bats
Added Gherkin (Feature File) support.  We currently use `prettier-plugin-gherkin` for linting our feature files, and we use the aspect_rules_lint for everything else.  Wanted to add this feature so we don't have to maintain a one off.
Adds a new feature for users to use `prettier-plugin-gherkin` w `prettier` to add functionality to formatting feature files.
- Added an example
=> Add Gherkin Support

lint/clang_tidy.bzl
[`layering_check`](https://bazel.build/docs/bazel-and-cpp#toolchain-features) is a toolchain feature that can track whether `#include` dependencies are properly represented in the bazel dependency graph. It is only supported with `clang` as the compiler.  Turning on this feature affects the internals of the c++ build rules, breaking an interaction with `lint_clang_tidy_aspect`. This leads to a build error looking like:
```
ERROR: .../BUILD.bazel:16:10: in //:linters.bzl%clang_tidy aspect on cc_binary rule //:executable:
Traceback (most recent call last):
File ".../external/aspect_rules_lint+/lint/clang_tidy.bzl", line 391, column 26, in _clang_tidy_aspect_impl
clang_tidy_action(ctx, compilation_context, ctx.executable, files_to_lint, outputs.human.out, outputs.human.exit_code)
File …
```
=> Disable `layering_check` in `lint_clang_tidy_aspect` evaluation

example/src/cpp/lib/BUILD, example/src/cpp/lib/hello-time.cc, lint/clang_tidy.bzl
The clang_tidy aspect did not read the `defines` and `local_defines` attribute of the rule, causing clang_tidy to error 
on parsing code that references these defines. This PR extends the clang_tidy.bzl with support for reading these attributes and adds them to the clang-tidy commandline. 
I also added a guard against rules that do not have a `srcs` attribute, but do return a CcInfo. 
---
Extended the example with a `local_defines` attribute and tried to lint the code without my changes, where i got the 
error 
```
_main/src/cpp/lib/hello-time.cc:16:28: error: use of undeclared identifier 'LOCAL_DEFINE_IS_DEFINED' [clang-diagnostic-error]
static const char* str = LOCAL_DEFINE_IS_DEFINED;
```
after my change the error is …
=> fix: clang_tidy - Add defines and local_defines attributes to commandline args

.github/workflows/publish.yaml, .github/workflows/release.yml, example/src/cpp/lib/BUILD
Practice run to confirm new end-user documentation.
---
=> feat: configure new publish-to-bcr workflow

lint/spotbugs.bzl
spotbugs didn't return the right exitcode to bazel lint when there are violations. Add -exitcode flag to fix it.
Test: 
```
Failed case:
bazel lint //examples:examples-lib
Lint results for //examples:examples-lib:
.....
M V EI2: new io.security.Access.java may expose internal representation by storing an externally mutable object into Access.accessRules  At Access.java:[line 45]
.....
$ echo $?                                             
113
```
succeed case:
```
bazel lint  //examples:examples-lib
INFO: Invocation ID: ab914925-3fa7-4ccc-92db-2f370255c3e1
INFO: Analyzed target  //examples:examples-lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Aspect //tools/lint:linters.bzl%spotbugs of//examples:examples-lib up-to-date: …
```
=> fix: spotbugs exitcode

.github/workflows/publish.yaml, .github/workflows/release.yml
We now use the reusable workflow rather than a configured GitHub App.
https://github.com/bazelbuild/bazel-central-registry/pull/4060 was created by manually triggering the workflow from this PR branch.
---
=> chore: fix new BCR release

.github/workflows/publish.yaml, .github/workflows/release.yml
Appu found that the slsa-verifier hard-codes the usual semver pattern vX.Y.Z. I was too cute using a shorter one that looks like a GitHub actions major/minor.
Also fix permissions and secret.
=> chore: fix release

.bazelignore, .bazelrc, .github/workflows/ci.yaml, MODULE.bazel, WORKSPACE.bazel, docs/.bazelversion, docs/BUILD.bazel, docs/MODULE.bazel
Isolate stardoc in a new sub-module.
I cannot withstand slow releases due to stardoc having a bug (https://github.com/bazelbuild/stardoc/pull/243)
See also https://blog.aspect.build/experiment-with-buf-and-starlark-docgen for a more ambitious idea of discarding it completely.
=> refactor: forbid compiling protoc in root repository

lint/private/patcher.mjs
the write of writeStream in fs has buffer and needs a callback to know when it's done.
I seem to be experiencing cases where the patch file is empty. The simple fix was to move this to the sync variant.
fixes #510
=> Writing patch file incorrectly buffers

format/private/format.sh, format/test/ls-files_test.sh
Fixing format which doesn't handle properly folders names with spaces. When format is executed it fails since the folder is not found because it cuts name with spaces thus it's not complete folder name.
Example of folder: `complex_folder/{{ cookiecutter.name }}/src.go`
---
=> fix(format): Handle successfuly folders name which contain spaces

lint/shellcheck.bzl
The `.shellcheckrc` file that can be specified through the `config` parameter in [lint_shellcheck_aspect](https://github.com/aspect-build/rules_lint/blob/main/docs/shellcheck.md#lint_shellcheck_aspect) appears to be ignored when it's specified anywhere other than the root of the repository.
I'm not sure if it's a desired design to want the config file at the root, but I decided to add the support for specifying it elsewhere in case it is not.
Manual testing for reproducing:
On `main` (at the root of the repo), move into the `example/` directory:
```
cd example
```
Note that running the `//test:shellcheck` test leads to failure (expected):
```
bazel test //test:shellcheck
```
We can make the test pass by appending these disable directives to the `.shellcheckrc`:
```
disable=SC2063 …
```
=> Specify `--rcfile` shellcheck option in `_shellcheck_aspect_impl`

.github/workflows/release.yml
Fixes publish failure in https://github.com/aspect-build/rules_lint/actions/runs/14410748994/job/40417851773
=> fix: when pushing a tag, use the ref_name as the tag

.aspect/workflows/.bazelrc, .aspect/workflows/config.yaml, .github/workflows/ci.yaml, docs/.bazelrc, docs/BUILD.bazel, docs/MODULE.bazel, docs/defs.bzl, docs/tools/BUILD.bazel, format/test/format_test.bats
Will replace our GitHub Actions CI, so we get persistent CI runners, buildbarn cache/RBE, and a web UI
=> chore: add config for Aspect Workflows

lint/private/patcher.mjs
openSync returns an fd and not an object so the call to `close` on it causes a failure.
Change to according closeSync call
fixes #524
=> Change close to work with fs sync methods

example/tools/format/(special_char)/[square]/hello.ts, example/tools/format/BUILD.bazel, format/defs.bzl
Some filenames can contain special chars, especially things like Nextjs app router file where they use `()` and `[]` to do grouping and wildcard.
Group `srcs` into a filegroup since `$(location <filename>)` won't work.
---
=> group srcs into filegroup to handle special char filename

.bcr/patches/go_dev_deps.patch, .gitattributes, .github/workflows/ci.yaml, MODULE.bazel
Reverts aspect-build/rules_lint#543
I forgot that the export-subst can only perform a substitution in a single file, for whatever reason...
=> Revert "refactor: simplify devDep patching"

docs/linting.md
Improve documentation on making lint failures fail builds. Previously it wasn't clear exactly what to put in .bazelrc to make this work.
Fixes https://github.com/aspect-build/rules_lint/issues/550.
=> Improve documentation on making lint failures fail builds

docs/format.md, format/defs.bzl, format/private/formatter_binary.bzl
Also fixes the BUILTIN_TOOL_LABELS entry for ruff so it shows up in the docs.
Part of https://github.com/aspect-build/rules_lint/issues/551.
=> Clarify how to use built-in formatters

docs/buf.md, docs/checkstyle.md, docs/clang-tidy.md, docs/eslint.md, docs/flake8.md, docs/keep_sorted.md, docs/ktlint.md, docs/lint_test.md, docs/pmd.md, docs/spotbugs.md, docs/stylelint.md, docs/vale.md, example/tools/lint/linters.bzl, lint/README.md, lint/buf.bzl, lint/checkstyle.bzl, lint/clang_tidy.bzl, lint/eslint.bzl, lint/flake8.bzl, lint/keep_sorted.bzl, lint/ktlint.bzl, lint/lint_test.bzl, lint/pmd.bzl, lint/spotbugs.bzl, lint/stylelint.bzl, lint/vale.bzl
Docs now match the actual usage and the examples, and use `Label` instead of `@@`. This is done for all linters except ruff and shellcheck, which are already being done in https://github.com/aspect-build/rules_lint/pull/563.
Part of https://github.com/aspect-build/rules_lint/issues/551.
=> Update the docs for all linters

README.md, docs/format.md, example/MODULE.bazel, example/WORKSPACE.bazel, example/src/BUILD.bazel, example/src/hello.toml, example/tools/format/BUILD.bazel, format/private/filter.jq, format/private/format.sh, format/private/formatter_binary.bzl, format/test/BUILD.bazel, format/test/format_test.bats
This patch adds formatting for [TOML](https://toml.io/en/) files. TOML is often used to configure various tooling and languages
(for example, `.ruff.toml`, `pyproject.toml`, `Cargo.toml`).
I chose to use [taplo](https://taplo.tamasfe.dev/) directly as the formatter, although my first attempt used [prettier-plugin-toml](https://www.npmjs.com/package/prettier-plugin-toml). My company isn't very js-focused so that obtaining `taplo` directly is much simpler than going over `prettier`.
`taplo` has some linting features, not implemented here, as we don't use them where I work and I don't know them.
---
- Searched for relevant documentation and updated as needed: yes (`README.md`)
- …
=> feat: Format toml with taplo

example/src/BUILD.bazel
Came across this by looking at https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/492/steps/canvas?sid=019899a2-3956-42b0-91db-b1576ef8e0a2 so we should use the load statement and not rely on native rules
Relates to https://github.com/aspect-build/rules_lint/pull/593
=> build: load py_library in example/src/BUILD.bazel

example/tools/lint/linters.bzl, lint/eslint.bzl
eslint plugins often need the tsconfig
Include `ts_project(tsconfig)` as inputs to eslint aspect.
=> fix: include ts_project(tsconfig) in eslint inputs

docs/format.md, example/.swcrc, example/BUILD.bazel, example/src/BUILD.bazel, example/src/config.json5, example/src/tsconfig.json, format/private/format.sh, format/private/formatter_binary.bzl, format/test/format_test.bats
=> feat(formatter): handle JSON5 and JSON with Comments

README.md
A simple typo broke the parsing and rendering of the tools table
=> chore: fix markdown parsing issue

lint/clang_tidy.bzl
Solves #627 
---
Should enable the aspect to run on stuff in external modules now.
=> fix: clang-tidy in external modules: use full paths

format/private/format.sh
To format https://bazel.build/rules/lib/globals/module#include files.
---
- Breaking change (forces users to change their own code or config): yes
This change also include a new file pattern for starlark file discovery: `*.MODULE.bazel`, which is for included files as documented by https://bazel.build/rules/lib/globals/module#include
We have been using this patch for a while.
=> chore: Format '*.MODULE.bazel' files
